# Generated by Django 3.1.7 on 2021-03-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
